version: 0.1

#environment_variables:
#  plaintext:
#  key: "value"

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Nothing to do in post_build
artifacts:
  files:
    - **/*
  discard-paths: no
