version: 0.1

environment_variables:
  plaintext:
    #AWS_REGION: "us-east-1"
    APP_NAME: "hapi-api"
    ECR_REPO: "hapi-api"
    DEPLOY_TO_ECS_CLUSTER: "true"
    ECS_CLUSTER: "testhapi-api"
    ECS_SERVICE: "hapi-api-service"
    ECS_TASK: "hapi-api-task"
    ECS_TASK_PORTMAPPINGS: "[{containerPort=9000,hostPort=80,protocol=tcp}]"
    ECS_CONTAINER: "hapi-api-container"


phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - tar czf ${APP_NAME}.tar.gz *
  post_build:
    commands:
      - /usr/bin/env bash ./deploy-ecs.sh
artifacts:
  files:
    - ${APP_NAME}.gz
  discard-paths: yes
