version: 0.1

#environment_variables:
#  plaintext:
#  key: "value"

phases:
  install:
    commands:
      - echo Nothing to do in install.
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
  post_build:
    commands:
      - echo Nothing to do in post_build
#artifacts:
#  files:
#    - location
#    - location
#  discard-paths: yes
