version: 0.1

environment_variables:
  plaintext:
    #AWS_REGION: "us-east-1"
    ECR_REPO: "weitest/hapi-api"

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - tar czf hapi-api.tar.gz *
  post_build:
    commands:
      - /usr/bin/env bash ./push-ecs-repo.sh
artifacts:
  files:
    - hapi-api.tar.gz
  discard-paths: yes
