version: 0.1

environment_variables:
  plaintext:
    #AWS_REGION: "us-east-1"
    GIT_BRANCH: "HEAD"
    ECR_REPO: "weitest/hapi-api"
    AWS_ACCOUNT_ID: "set your account ID in build project"

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - tar czf hapi-api.tar.gz *
  post_build:
    commands:
      - echo "source version: ${CODEBUILD_SOURCE_VERSION}"
      - eval $(aws --region ${AWS_REGION} ecr get-login)
      - docker build -t ${ECR_REPO}:latest .
      #- echo "Deploying docker build (version:$(git rev-parse $GIT_BRANCH | head -c 8)) to account: ${AWS_ACCOUNT_ID} ECR repo: ${ECR_REPO}"
      # - docker tag ${ECR_REPO}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
      - echo "Publish as ${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}"
      # - docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${CODEBUILD_SOURCE_VERSION}
artifacts:
  files:
    - hapi-api.tar.gz
  discard-paths: yes
