version: 0.1

environment_variables:
  plaintext:
    AWS_REGION: "us-east-1"

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - tar czf hapi-api.tar.gz *
  post_build:
    commands:
      - uuid=$(date +%s)
      - eval $(aws --region ${AWS_REGION} ecr get-login)
      - echo ${uuid}
artifacts:
  files:
    - hapi-api.tar.gz
  discard-paths: yes
