version: 0.1

environment_variables:
  plaintext:
    AWS_REGION: "us-east-1"
    GIT_BRANCH: "HEAD"
    LOCAL_REPO: "hapi-api"
    ECR_REPO: "weitest/hapi-api"
    AWS_ACCOUNT_ID: "set your account ID in build project"

phases:
  install:
    commands:
      - apt-get update -y
      - curl -sL https://deb.nodesource.com/setup_6.x | bash -
      - apt-get install -y nodejs

  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm test
      - tar czf hapi-api.tar.gz *
  post_build:
    commands:
      - eval $(aws --region ${AWS_REGION} ecr get-login)
      - docker build -t {ECR_REPO}:latest .
      - echo "Deploying docker build to account: ${AWS_ACCOUNT_ID} ECR repo: ${ECR_REPO}"
      - BUILD_VERSION=$(git rev-parse $GIT_BRANCH | head -c 8) && docker tag ${ECR_REPO}:latest ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/weitest/hapi-api:${BUILD_VERSION} && docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/weitest/hapi-api:${BUILD_VERSION}
artifacts:
  files:
    - hapi-api.tar.gz
  discard-paths: yes
